export default [{
  "type": "placement-assets",
  "keyFrames": [{
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "T000044192",
                  "subject_name": "中国建材集团",
                  "type_code": "actual_shareholder",
                  "type_name": "实际控制人",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "T000044192",
                  "type": "actualController",
                  "name": "中国建材集团",
                  "logo": "actual-holder"
              },
              {
                  "subject_id": "00004195",
                  "subject_name": "中国建材",
                  "type_code": "controlling_shareholder",
                  "type_name": "控股股东",
                  "value": "26.73%",
                  "explain": "26.73%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00004195",
                  "type": "shareholder",
                  "init": true,
                  "name": "中国建材",
                  "actualController_id": "T000044192",
                  "logo": "control-holder",
                  "first_final": true,
                  "last_value": "0.2673",
                  "trade_value": ""
              },
              {
                  "subject_id": "00074796",
                  "subject_name": "祁连山建材控股",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "11.80%",
                  "explain": "11.80%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00074796",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "T000044192",
                  "name": "祁连山建材控股",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.1180",
                  "trade_value": ""
              },
              {
                  "subject_id": "qtgd",
                  "subject_name": "其他股东",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "73.27%",
                  "explain": "73.27%",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qtgd",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "其他股东",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.7327",
                  "trade_value": ""
              },
              {
                  "subject_id": "qbzcjfz",
                  "subject_name": "全部资产及负债",
                  "type_code": "assets",
                  "type_name": "资产",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qbzcjfz",
                  "type": "assets",
                  "init": true,
                  "name": "全部资产及负债",
                  "logo": "assets",
                  "is_active1": 1
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "00004195",
                  "subject_name": "中国建材",
                  "type_code": "controlling_shareholder",
                  "type_name": "控股股东",
                  "value": "26.73%",
                  "explain": "26.73%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00004195",
                  "type": "shareholder",
                  "init": true,
                  "name": "中国建材",
                  "actualController_id": "T000044192",
                  "logo": "control-holder",
                  "first_final": true,
                  "last_value": "0.2673",
                  "trade_value": ""
              },
              {
                  "subject_id": "00074796",
                  "subject_name": "祁连山建材控股",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "11.80%",
                  "explain": "11.80%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00074796",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "T000044192",
                  "name": "祁连山建材控股",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.1180",
                  "trade_value": ""
              },
              {
                  "subject_id": "qtgd",
                  "subject_name": "其他股东",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "73.27%",
                  "explain": "73.27%",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qtgd",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "其他股东",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.7327",
                  "trade_value": ""
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "",
                  "value": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "value": ""
              },
              {
                  "subject_id": "qbzcjfz",
                  "subject_name": "全部资产及负债",
                  "type_code": "assets",
                  "type_name": "资产",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qbzcjfz",
                  "type": "assets",
                  "init": true,
                  "name": "全部资产及负债",
                  "logo": "assets",
                  "is_active1": 1
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "00004195",
                  "subject_name": "中国建材",
                  "type_code": "controlling_shareholder",
                  "type_name": "控股股东",
                  "value": "26.73%",
                  "explain": "26.73%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00004195",
                  "type": "shareholder",
                  "init": true,
                  "name": "中国建材",
                  "actualController_id": "T000044192",
                  "logo": "control-holder",
                  "first_final": true,
                  "last_value": "0.2673",
                  "trade_value": ""
              },
              {
                  "subject_id": "00074796",
                  "subject_name": "祁连山建材控股",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "11.80%",
                  "explain": "11.80%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00074796",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "T000044192",
                  "name": "祁连山建材控股",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.1180",
                  "trade_value": ""
              },
              {
                  "subject_id": "qtgd",
                  "subject_name": "其他股东",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "73.27%",
                  "explain": "73.27%",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qtgd",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "其他股东",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.7327",
                  "trade_value": ""
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "",
                  "value": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "value": ""
              },
              {
                  "subject_id": "qbzcjfz",
                  "subject_name": "全部资产及负债",
                  "type_code": "assets",
                  "type_name": "资产",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qbzcjfz",
                  "type": "assets",
                  "init": true,
                  "name": "全部资产及负债",
                  "logo": "assets",
                  "is_active1": 1
              },
              {
                  "id": "00009605",
                  "name": "一公院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "00012062",
                  "name": "二公院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T002991047",
                  "name": "西南院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T001887911",
                  "name": "东北院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "Q000688CCC",
                  "name": "能源院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T000114542",
                  "name": "公规院",
                  "type": "transactionAssets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "00004195",
                  "subject_name": "中国建材",
                  "type_code": "controlling_shareholder",
                  "type_name": "控股股东",
                  "value": "26.73%",
                  "explain": "26.73%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00004195",
                  "type": "shareholder",
                  "init": true,
                  "name": "中国建材",
                  "actualController_id": "T000044192",
                  "logo": "control-holder",
                  "first_final": true,
                  "last_value": "26.73%",
                  "trade_value": "",
                  "tempvalue": "26.73%"
              },
              {
                  "subject_id": "00074796",
                  "subject_name": "祁连山建材控股",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "11.80%",
                  "explain": "11.80%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00074796",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "T000044192",
                  "name": "祁连山建材控股",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "11.80%",
                  "trade_value": "",
                  "tempvalue": "11.80%"
              },
              {
                  "subject_id": "qtgd",
                  "subject_name": "其他股东",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "73.27%",
                  "explain": "73.27%",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qtgd",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "其他股东",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "73.27%",
                  "trade_value": "",
                  "tempvalue": "73.27%"
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "",
                  "value": "",
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "0",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "value": "",
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "subject_id": "qbzcjfz",
                  "subject_name": "全部资产及负债",
                  "type_code": "assets",
                  "type_name": "资产",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qbzcjfz",
                  "type": "transactionAssets",
                  "init": true,
                  "name": "全部资产及负债",
                  "logo": "assets",
                  "is_active1": 1
              },
              {
                  "id": "00009605",
                  "name": "一公院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "00012062",
                  "name": "二公院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T002991047",
                  "name": "西南院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T001887911",
                  "name": "东北院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "Q000688CCC",
                  "name": "能源院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T000114542",
                  "name": "公规院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "00004195",
                  "subject_name": "中国建材",
                  "type_code": "controlling_shareholder",
                  "type_name": "控股股东",
                  "value": "26.73%",
                  "explain": "26.73%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00004195",
                  "type": "shareholder",
                  "init": true,
                  "name": "中国建材",
                  "actualController_id": "",
                  "logo": "control-holder",
                  "first_final": true,
                  "last_value": "0.2673"
              },
              {
                  "subject_id": "00074796",
                  "subject_name": "祁连山建材控股",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "11.80%",
                  "explain": "11.80%",
                  "relate_id": "T000044192",
                  "group": "not_merge",
                  "id": "00074796",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "祁连山建材控股",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.1180"
              },
              {
                  "subject_id": "qtgd",
                  "subject_name": "其他股东",
                  "type_code": "shareholder",
                  "type_name": "股东",
                  "value": "73.27%",
                  "explain": "73.27%",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "qtgd",
                  "type": "shareholder",
                  "init": true,
                  "actualController_id": "",
                  "name": "其他股东",
                  "logo": "holder",
                  "first_final": true,
                  "last_value": "0.7327"
              },
              {
                  "id": "00009605",
                  "name": "一公院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "00012062",
                  "name": "二公院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T002991047",
                  "name": "西南院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T001887911",
                  "name": "东北院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "Q000688CCC",
                  "name": "能源院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "T000114542",
                  "name": "公规院",
                  "type": "assets",
                  "logo": "son_company",
                  "value": "100%股权",
                  "explain": "100%股权",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": "100%股权"
              }
          ],
          "edges": []
      }
  ]
},
{
  "type": "shares-purchase-assets",
  "keyFrames": [{
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "26.73%",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "11.80%",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "73.27%",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "26.73%",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "11.80%",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "73.27%",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "26.73%",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "11.80%",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "73.27%",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "zczhcebf",
                  "name": "资产置换差额部分",
                  "type": "transactionAssets",
                  "logo": "assets",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "26.73%",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": "26.73%"
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "11.80%",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": "11.80%"
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "73.27%",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": "73.27%"
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": "",
                  "tempvalue": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "transactionShareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": "",
                  "tempvalue": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "zczhcebf",
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "logo": "assets",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "03138697",
                  "name": "中国交建",
                  "type": "shareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "id": "00079021",
                  "name": "中国城乡",
                  "type": "shareholder",
                  "relate_id": "00090712",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "1",
                  "tradingObj": true,
                  "actualController_id": "00090712",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "id": "zczhcebf",
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "logo": "assets",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      }
  ]
},
{
  "type": "shares-raise-funds",
  "keyFrames": [{
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国交建",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "03138697",
                  "group": "not_merge",
                  "type_code": "controlling_shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国城乡",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "00079021",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "explain": "",
                  "value": "",
                  "init": true,
                  "id": "zczhcebf",
                  "logo": "assets",
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国交建",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "03138697",
                  "group": "not_merge",
                  "type_code": "controlling_shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国城乡",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "00079021",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "bcg35mtddx-3",
                  "name": "不超过35名特定对象",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "2",
                  "tradingObj": true,
                  "actualController_id": "",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "explain": "",
                  "value": "",
                  "init": true,
                  "id": "zczhcebf",
                  "logo": "assets",
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国交建",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "03138697",
                  "group": "not_merge",
                  "type_code": "controlling_shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国城乡",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "00079021",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "bcg35mtddx-3",
                  "name": "不超过35名特定对象",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "2",
                  "tradingObj": true,
                  "actualController_id": "",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "explain": "",
                  "value": "",
                  "init": true,
                  "id": "zczhcebf",
                  "logo": "assets",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "xj-3",
                  "name": "现金",
                  "type": "transactionAssets",
                  "logo": "cash",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "name": "中国交建",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "03138697",
                  "group": "not_merge",
                  "type_code": "controlling_shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "name": "中国城乡",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "00079021",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": "",
                  "tempvalue": ""
              },
              {
                  "id": "bcg35mtddx-3",
                  "name": "不超过35名特定对象",
                  "type": "transactionShareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "2",
                  "tradingObj": true,
                  "actualController_id": "",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": "",
                  "tempvalue": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "explain": "",
                  "value": "",
                  "init": true,
                  "id": "zczhcebf",
                  "logo": "assets",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "xj-3",
                  "name": "现金",
                  "type": "assets",
                  "logo": "cash",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      },
      {
          "nodes": [{
                  "id": "600720",
                  "code": "600720",
                  "codeName": "祁连山",
                  "type": "company",
                  "is_transaction": true
              },
              {
                  "subject_id": "00090712",
                  "subject_name": "中交集团",
                  "type_code": "actual_shareholder",
                  "type_name": "实际控制人",
                  "value": "",
                  "explain": "",
                  "relate_id": "",
                  "group": "not_merge",
                  "id": "00090712",
                  "type": "actualController",
                  "name": "中交集团",
                  "logo": "actual-holder"
              },
              {
                  "name": "中国建材",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00004195",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "祁连山建材控股",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "00074796",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "其他股东",
                  "type": "shareholder",
                  "actualController_id": "",
                  "value": "",
                  "init": true,
                  "id": "qtgd",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国交建",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "03138697",
                  "group": "not_merge",
                  "type_code": "controlling_shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "name": "中国城乡",
                  "type": "shareholder",
                  "actualController_id": "00090712",
                  "value": "",
                  "init": true,
                  "new_holder": "1",
                  "id": "00079021",
                  "group": "not_merge",
                  "type_code": "shareholder",
                  "trade_value": "",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "bcg35mtddx-3",
                  "name": "不超过35名特定对象",
                  "type": "shareholder",
                  "relate_id": "",
                  "group": "not_merge",
                  "trade_value": "",
                  "new_holder": "2",
                  "tradingObj": true,
                  "actualController_id": "",
                  "first_final": true,
                  "last_value": "",
                  "type_code": "shareholder",
                  "value": ""
              },
              {
                  "name": "一公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00009605",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "二公院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "00012062",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "西南院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T002991047",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "东北院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T001887911",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "能源院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "Q000688CCC",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "公规院",
                  "type": "assets",
                  "explain": "100%股权",
                  "value": "100%股权",
                  "init": true,
                  "id": "T000114542",
                  "logo": "son_company",
                  "first_final": true,
                  "last_value": "100%股权"
              },
              {
                  "name": "资产置换差额部分",
                  "type": "assets",
                  "explain": "",
                  "value": "",
                  "init": true,
                  "id": "zczhcebf",
                  "logo": "assets",
                  "first_final": true,
                  "last_value": ""
              },
              {
                  "id": "xj-3",
                  "name": "现金",
                  "type": "assets",
                  "logo": "cash",
                  "value": "",
                  "explain": "",
                  "is_active1": 0,
                  "tradingfromObj": true,
                  "first_final": true,
                  "last_value": ""
              }
          ],
          "edges": []
      }
  ]
}
]